%%
%% This is file `korigamik.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% korigamik.dtx  (with options: `class')
%% ---------:| ----------------------------------------------------------
%% korigamik:| KorigamiK LaTeX Template
%%    Author:| Kushagra Lakhwani
%%    E-mail:| korigamik@gmail.com
%%   License:| Released under the GNU General Public License v3 or later
%%       See:| http://www.gnu.org/licenses/


\NeedsTeXFormat{LaTeX2e}[1999/12/01]
\ProvidesClass{korigamik}
    [2023/06/24 v1.00 KorigamiK LaTeX Template]
\LoadClass[a4paper,fleqn]{article}
\newcommand{\dummyMacro}{}
\newenvironment{dummyEnv}{%
}{%
}
%% 
%% Copyright (C) 2023 by Kushagra Lakhwani <korigamik@gmail.com>
%% 
%% KorigamiK class is free software: you can redistribute it and/or modify
%% it under the terms of the GNU General Public License as published by
%% the Free Software Foundation, either version 3 of the License, or (at
%% your option) any later version.
%% 
%% KorigamiK class is distributed in the hope that it will be useful, but
%% WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%% General Public License for more details.
%% 
%% You should have received a copy of the GNU General Public License
%% along with KorigamiK class.  If not, see <http://www.gnu.org/licenses/>.
%% 
%%
%% End of file `korigamik.cls'.
